logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug
    com.ldsj: debug

wx:
  pay:
    appId: wxae6b55******1  #微信公众号或者小程序等的appid
    mchId: 15******   #微信支付商户号
    mchKey: se*********se   #微信支付商户密钥
    keyPath: classpath:wxcert/apiclient_cert.p12    #p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    #subAppId:  #服务商模式下的子商户公众账号ID
    #subMchId:  #服务商模式下的子商户号
    
spring:
  mvc:
    static-path-pattern: /static/**